# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: ^tsconfig
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # Ruff configuration is found in flask/pyproject.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
