x-docker-env-overrides: &docker-env-overrides
  MONGO_URI: mongodb://odt-db/oligo_db
  REDIS_URI: redis://odt-redis

services:
  odt-db:
    image: mongo:8

  odt-redis:
    image: redis:8-alpine

  odt-server:
    image: ghcr.io/helmholtzai-consultants-munich/odt-server:testing
    build:
      dockerfile: docker/server.Dockerfile
    volumes:
      - data-access:/app/backend/data-access
    env_file: .env
    environment: *docker-env-overrides
    depends_on:
      - odt-db
      - odt-redis

  odt-beat:
    image: ghcr.io/helmholtzai-consultants-munich/odt-server:testing
    build:
      dockerfile: docker/server.Dockerfile
    env_file: .env
    environment: *docker-env-overrides
    depends_on:
      - odt-db
      - odt-redis
      - odt-worker
    command: celery -A backend.beat beat

  odt-worker:
    image: ghcr.io/helmholtzai-consultants-munich/odt-worker:testing
    build:
      dockerfile: docker/worker.Dockerfile
    volumes:
      - data-access:/app/backend/data-access
      - cache:/app/backend/cache
    env_file: .env
    environment: *docker-env-overrides
    depends_on:
      - odt-db
      - odt-redis

  odt-web:
    image: ghcr.io/helmholtzai-consultants-munich/odt-web:testing
    build:
      dockerfile: docker/web.Dockerfile
      args:
        # This syntax passes through vars from .env
        VITE_BACKEND_URL:
        VITE_FEEDBACK_MAX_LENGTH:
        VITE_TURNSTILE_SITE_KEY:

  odt-mongodb-exporter:
    image: percona/mongodb_exporter:0.47.2
    command:
      - "--mongodb.uri=mongodb://odt-db:27017"
      - "--collect-all"
    depends_on:
      - odt-db
    profiles: [monitoring]

  odt-node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /:/host:ro
    profiles: [monitoring]

  odt-cadvisor:
    image: ghcr.io/google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    profiles: [monitoring]

  odt-prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    profiles: [monitoring]

  odt-grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - odt-prometheus
    profiles: [monitoring]

volumes:
  data-access:
  cache:
