services:
  mongodb:
    image: mongo:8
    container_name: odt-mongodb
  
  odt-server:
    image: odt-server
    build: ./flask
    container_name: odt-server
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://mongodb:27017/oligo_db
    volumes:
      # bind mount source for development 
      - ./flask:/app:ro
      # volume mount data for write permission
      - /app/cache
      - /app/uploads
      - /app/user_data
