services:
  odt-db:
    image: mongo:8
    container_name: odt-db
    # Comment out these lines to restrict database access to containers
    ports:
      - 27017:27017
    restart: on-failure

  odt-mq:
    image: rabbitmq:4
    container_name: odt-mq
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

  odt-server:
    image: odt-server
    build:
      dockerfile: docker/server.Dockerfile
    container_name: odt-server
    ports:
      - 5000:5000
    environment:
      MONGO_URI: mongodb://odt-db:27017/oligo_db
      CELERY_MONGO_URI: mongodb://odt-db:27017/
      CELERY_BROKER: pyamqp://guest@odt-mq/
    depends_on:
      - odt-db
      - odt-mq
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: ./flask
          target: /app
          initial_sync: true

  odt-worker:
    image: odt-worker
    build:
      dockerfile: docker/worker.Dockerfile
    container_name: odt-worker
    environment:
      CELERY_MONGO_URI: mongodb://odt-db:27017/
      CELERY_BROKER: pyamqp://guest@odt-mq/
    depends_on:
      - odt-db
      - odt-mq
    restart: on-failure
    develop:
      watch:
        - action: sync+restart
          path: ./flask/worker
          target: /app/worker
          initial_sync: true

  odt-web:
    image: odt-web
    build:
      dockerfile: docker/web.Dockerfile
    container_name: odt-web
    ports:
      - 3000:3000
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          initial_sync: true

  odt-tests:
    image: odt-tests
    build:
      dockerfile: docker/tests.Dockerfile
    container_name: odt-tests
    network_mode: host # this should be removed once the URL is configurable
    environment:
      PLAYWRIGHT_HTML_OUTPUT_DIR: /app/tests/playwright-report
    depends_on:
      - odt-web
      - odt-server
    restart: no
    profiles: [tests] # don't run unless specified
