/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "FastaFormUpload".
 */
export type FastaFormUpload =
    | NcbiFastaFormDataUncommented
    | EnsFastaFormDataUncommented;

export interface OdtFastaForm {
    files_fasta_target_probe_database: FastaFormUncommented[];
    files_fasta_reference_database_target_probe: FastaFormUncommented[];
    files_fasta_reference_database_readout_probe: FastaFormUncommented[];
    files_fasta_reference_database_primer: FastaFormUncommented[];
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "FastaFormUncommented".
 */
export interface FastaFormUncommented {
    selectedSource: string;
    formDataNcbi: NcbiFastaFormDataUncommented;
    formDataEns: EnsFastaFormDataUncommented;
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "NcbiFastaFormDataUncommented".
 */
export interface NcbiFastaFormDataUncommented {
    dir_output: string;
    source: string;
    source_params: NcbiSourceParamsUncommented;
    genomic_regions: GenomicRegionsUncommented;
    exon_exon_junction_block_size: string;
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "NcbiSourceParamsUncommented".
 */
export interface NcbiSourceParamsUncommented {
    species: string;
    annotation_release: string;
    taxon: string;
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "GenomicRegionsUncommented".
 */
export interface GenomicRegionsUncommented {
    gene: string;
    intergenic: string;
    exon: string;
    exon_exon_junction: string;
    utr: string;
    cds: string;
    intron: string;
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "EnsFastaFormDataUncommented".
 */
export interface EnsFastaFormDataUncommented {
    dir_output: string;
    source: string;
    source_params: EnsSourceParamsUncommented;
    genomic_regions: GenomicRegionsUncommented;
    exon_exon_junction_block_size: string;
}
/**
 * This interface was referenced by `OdtFastaForm`'s JSON-Schema
 * via the `definition` "EnsSourceParamsUncommented".
 */
export interface EnsSourceParamsUncommented {
    species: string;
    annotation_release: string;
}
