global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # MongoDB metrics
  - job_name: "mongodb"
    static_configs:
      - targets: ["odt-mongodb-exporter:9216"]
    metrics_path: "/metrics"

  # Flask server metrics
  - job_name: "odt-server"
    static_configs:
      - targets: ["odt-server:8000"]
    metrics_path: "/metrics"

  # Host OS metrics (node_exporter)
  - job_name: "node"
    static_configs:
      - targets: ["odt-node-exporter:9100"]
    metrics_path: "/metrics"

  # Container metrics (cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["odt-cadvisor:8080"]
    metrics_path: "/metrics"
