n_jobs: 1
dir_output: /Users/yarkineren/WebstormProjects/untitled/flask/user_data/testuser123/output_seqfish_probe_designer_2025-08-18_13-26-12
write_intermediate_steps: false
top_n_sets: 3
file_regions: /var/folders/b8/ckhxj97x2svcv7j3zv11bj2r0000gn/T/tmp0kh1l0xe.txt
files_fasta_target_probe_database:
- target1.fna
files_fasta_reference_database_target_probe:
- ref1.fna
target_probe_length_min: 20
target_probe_length_max: 40
target_probe_isoform_consensus: 1
target_probe_GC_content_min: 30
target_probe_GC_content_opt: 50
target_probe_GC_content_max: 70
target_probe_T_secondary_structure: 2
target_probe_secondary_structures_threshold_deltaG: 10
target_probe_homopolymeric_base_n:
  A: 3
  T: 3
  C: 3
  G: 3
target_probe_GC_weight: 1
target_probe_UTR_weight: 1
set_size_min: 10
set_size_opt: 15
distance_between_target_probes: 5
n_sets: 1
files_fasta_reference_database_readout_probe:
- readout1.fna
readout_probe_base_probabilities:
  A: 25
  T: 25
  C: 25
  G: 25
readout_probe_length: 20.0
readout_probe_GC_content_min: 30
readout_probe_GC_content_max: 70
readout_probe_homopolymeric_base_n:
  G: 3
n_barcode_rounds: 4
n_pseudocolors: 4
channels_ids: 0,1,2,3
files_fasta_reference_database_primer:
- primer1.fna
reverse_primer_sequence: ACTGACTGACTG
primer_length: 20
primer_base_probabilities:
  A: 25
  T: 25
  C: 25
  G: 25
primer_GC_content_min: 30
primer_GC_content_max: 70
primer_number_GC_GCclamp: 2
primer_number_three_prime_base_GCclamp: 1
primer_homopolymeric_base_n:
  A: 3
  T: 3
  C: 3
  G: 3
primer_max_len_selfcomplement: 4
primer_max_len_complement_reverse_primer: 4
primer_Tm_min: 60
primer_Tm_max: 70
primer_T_secondary_structure: 2
primer_secondary_structures_threshold_deltaG: 10
target_probe_specificity_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
  max_hsps: 10
target_probe_specificity_blastn_hit_parameters:
  min_alignment_length: 18
target_probe_cross_hybridization_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
target_probe_cross_hybridization_blastn_hit_parameters:
  min_alignment_length: 18
max_graph_size: 1000
n_attempts: 3
heuristic: false
heuristic_n_attempts: 2
readout_probe_initial_num_sequences: 100
readout_probe_specificity_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
  max_hsps: 10
readout_probe_specificity_blastn_hit_parameters:
  min_alignment_length: 18
readout_probe_cross_hybridization_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
readout_probe_cross_hybridization_blastn_hit_parameters:
  min_alignment_length: 18
primer_initial_num_sequences: 100
primer_specificity_refrence_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
  max_hsps: 10
primer_specificity_refrence_blastn_hit_parameters:
  min_alignment_length: 18
primer_specificity_encoding_probes_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
  dust: 'yes'
  soft_masking: 'true'
  max_target_seqs: 500
  max_hsps: 10
primer_specificity_encoding_probes_blastn_hit_parameters:
  min_alignment_length: 18
primer_Tm_parameters:
  nn_table: DNA_NN1
  tmm_table: DNA_TMM1
  imm_table: DNA_IMM1
  de_table: DNA_DE1
  dnac1: 50
  dnac2: 50
  saltcorr: 1
  Na: 50
  K: 50
  Tris: 10
  Mg: 1
  dNTPs: '0.2'
primer_Tm_chem_correction_parameters: null
primer_Tm_salt_correction_parameters: null
