n_jobs: 1
dir_output: /Users/yarkineren/WebstormProjects/untitled/flask/user_data/testuser123/output_oligoseq_probe_designer_2025-09-04_10-36-52
write_intermediate_steps: false
top_n_sets: 3
file_regions: /var/folders/b8/ckhxj97x2svcv7j3zv11bj2r0000gn/T/tmpun3tmo3p.txt
files_fasta_target_probe_database:
- target1.fna
files_fasta_reference_database_target_probe:
- ref1.fna
target_probe_length_min: 20
target_probe_length_max: 40
target_probe_split_region: 1
target_probe_targeted_exons: 1
target_probe_isoform_consensus: 1
target_probe_GC_content_min: 30
target_probe_GC_content_opt: 50
target_probe_GC_content_max: 70
target_probe_Tm_min: 60
target_probe_Tm_opt: 65
target_probe_Tm_max: 70
target_probe_secondary_structures_T: 2
target_probe_secondary_structures_threshold_deltaG: 10
target_probe_homopolymeric_base_n:
  A: 3
  T: 3
  C: 3
  G: 3
target_probe_max_len_selfcomplement: 4
target_probe_hybridization_probability_threshold: 0.8
target_probe_GC_weight: 1
target_probe_Tm_weight: 1
set_size_min: 10
set_size_opt: 15
distance_between_target_probes: 5
n_sets: 1
target_probe_hybridization_probability_alignment_method: bowtie
target_probe_hybridization_probability_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
target_probe_hybridization_probability_blastn_hit_parameters:
  coverage: 85
target_probe_hybridization_probability_bowtie_search_parameters:
  v: 3
  -nofw: 'true'
target_probe_cross_hybridization_alignment_method: bowtie
target_probe_cross_hybridization_blastn_search_parameters:
  perc_identity: 85
  strand: both
  word_size: 11
target_probe_cross_hybridization_blastn_hit_parameters:
  coverage: 85
target_probe_cross_hybridization_bowtie_search_parameters:
  -v: 3
  --nofw: 'true'
max_graph_size: 1000
n_attempts: 3
heuristic: false
heuristic_n_attempts: 2
target_probe_Tm_parameters:
  nn_table: DNA_NN1
  tmm_table: DNA_TMM1
  imm_table: DNA_IMM1
  de_table: DNA_DE1
  dnac1: 50
  dnac2: 50
  saltcorr: 1
  Na: 50
  K: 50
  Tris: 10
  Mg: 1
  dNTPs: '0.2'
target_probe_Tm_chem_correction_param_probe: null
target_probe_Tm_chem_correction_parameters:
  DMSO: 0
  fmd: 0
  DMSOfactor: 0.0
  fmdfactor: 0.0
  fmdmethod: 0
  GC: null
target_probe_Tm_salt_correction_parameters: null
target_probe_hybridization_probability_bowtie_hit_parameters: null
target_probe_cross_hybridization_bowtie_hit_parameters: null
