const formDatas = {
    n_jobs: 4,
    dir_output: "output_seqfishplus_probe_designer",
    write_intermediate_steps: true,
    top_n_sets: 3,
    file_regions: "",
    files_fasta_target_probe_database: [
        "data:application/octet-stream;name=placeholder;base64,",
    ],
    files_fasta_reference_database_target_probe: [
        "data:application/octet-stream;name=placeholder;base64,",
    ],
    target_probe_length_min: 28,
    target_probe_length_max: 28,
    target_probe_isoform_consensus: 100,
    target_probe_GC_content_min: 45,
    target_probe_GC_content_opt: 55,
    target_probe_GC_content_max: 65,
    target_probe_homopolymeric_base_n: {
        A: 5,
        T: 5,
        C: 5,
        G: 5,
    },
    target_probe_T_secondary_structure: 76,
    target_probe_secondary_structures_threshold_deltaG: 0,
    target_probe_GC_weight: 1,
    target_probe_UTR_weight: 10,
    set_size_min: 24,
    set_size_opt: 24,
    distance_between_target_probes: 2,
    n_sets: 100,
    files_fasta_reference_database_readout_probe: [
        "data:application/octet-stream;name=placeholder;base64,",
    ],
    readout_probe_length: 15,
    readout_probe_base_probabilities: {
        A: 0.25,
        C: 0.25,
        G: 0.25,
        T: 0.25,
    },
    readout_probe_GC_content_min: 40,
    readout_probe_GC_content_max: 60,
    readout_probe_homopolymeric_base_n: {
        G: 3,
    },
    n_barcode_rounds: 4,
    n_pseudocolors: 20,
    channels_ids: "Alexa488, Cy3b, Alexa647",
    files_fasta_reference_database_primer: [
        "data:application/octet-stream;name=placeholder;base64,",
    ],
    reverse_primer_sequence: "CCCTATAGTGAGTCGTATTA",
    primer_length: 20,
    primer_base_probabilities: {
        A: 0.25,
        C: 0.25,
        G: 0.25,
        T: 0.25,
    },
    primer_GC_content_min: 50,
    primer_GC_content_max: 65,
    primer_number_GC_GCclamp: 1,
    primer_number_three_prime_base_GCclamp: 2,
    primer_homopolymeric_base_n: {
        A: 4,
        T: 4,
        C: 4,
        G: 4,
    },
    primer_max_len_selfcomplement: 6,
    primer_max_len_complement_reverse_primer: 5,
    primer_Tm_min: 60,
    primer_Tm_max: 75,
    primer_T_secondary_structure: 76,
    primer_secondary_structures_threshold_deltaG: 0,
    target_probe_specificity_blastn_search_parameters: {
        perc_identity: 100,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
        max_hsps: 1000,
    },
    target_probe_specificity_blastn_hit_parameters: {
        min_alignment_length: 15,
    },
    target_probe_cross_hybridization_blastn_search_parameters: {
        perc_identity: 80,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
    },
    target_probe_cross_hybridization_blastn_hit_parameters: {
        min_alignment_length: 17,
    },
    max_graph_size: 5000,
    n_attempts: 100000,
    heuristic: true,
    heuristic_n_attempts: 100,
    readout_probe_initial_num_sequences: 100000,
    readout_probe_specificity_blastn_search_parameters: {
        perc_identity: 100,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
        max_hsps: 1000,
    },
    readout_probe_specificity_blastn_hit_parameters: {
        min_alignment_length: 10,
    },
    readout_probe_cross_hybridization_blastn_search_parameters: {
        perc_identity: 100,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
    },
    readout_probe_cross_hybridization_blastn_hit_parameters: {
        min_alignment_length: 10,
    },
    primer_initial_num_sequences: 1000000,
    primer_specificity_refrence_blastn_search_parameters: {
        perc_identity: 100,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
        max_hsps: 1000,
    },
    primer_specificity_refrence_blastn_hit_parameters: {
        min_alignment_length: 14,
    },
    primer_specificity_encoding_probes_blastn_search_parameters: {
        perc_identity: 100,
        strand: "minus",
        word_size: 7,
        dust: "no",
        soft_masking: "false",
        max_target_seqs: 10,
        max_hsps: 1000,
    },
    primer_specificity_encoding_probes_blastn_hit_parameters: {
        min_alignment_length: 11,
    },
    primer_Tm_parameters: {
        nn_table: "DNA_NN4",
        tmm_table: "DNA_TMM1",
        imm_table: "DNA_IMM1",
        de_table: "DNA_DE1",
        dnac1: 250,
        dnac2: 250,
        saltcorr: 5,
        Na: 300,
        K: 0,
        Tris: 0,
        Mg: 0,
        dNTPs: 0,
    },
    primer_Tm_chem_correction_parameters: null,
    primer_Tm_salt_correction_parameters: null,
};

export default formDatas;
