dir_output: output_genomic
exon_exon_junction_block_size: 50
genomic_regions:
  cds: true
  exon: true
  exon_exon_junction: true
  gene: true
  intergenic: true
  intron: true
  utr: true
source: ensembl
source_params:
  annotation_release: current
  species: Homo_sapiens
