dir_output: output_genomic
exon_exon_junction_block_size: 50
genomic_regions:
  cds: false
  exon: false
  exon_exon_junction: false
  gene: false
  intergenic: false
  intron: false
  utr: true
source: ncbi
source_params:
  annotation_release: 110
  species: Homo_sapiens
  taxon: vertebrate_mammalian
