[swarm]

[swarm:vars]
ansible_user = ubuntu
ansible_ssh_common_args = "-o ProxyCommand='ssh -o StrictHostKeyChecking=accept-new  -i ~/.ssh/odt-ansible-key -W %h:%p ubuntu@134.94.199.236' -o StrictHostKeyChecking=accept-new "
