plugin: openstack.cloud.openstack

all_projects: false
fail_on_errors: true
strict: true
legacy_groups: false
use_names: true
keyed_groups:
  - key: openstack.metadata.swarm_role
    prefix: swarm
    parent_group: swarm
