title: Oligo Designer Toolsuite
description: Frontend documentation
logo: /assets/images/logo.png
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Aux links in header
aux_links:
  "GitHub Repository":
    - "//github.com/HelmholtzAI-Consultants-Munich/oligo-designer-toolsuite-front-end"

# Enable search
search_enabled: true
search:
  heading_level: 3

# Navigation structure (order controls sidebar sequence)
nav_order: 1

# Base URL (set if publishing under a project page)
# baseurl: "/<repo>"
# url: "https://<user>.github.io"

plugins:
  - jekyll-seo-tag
