name: Deploy latest ODT Cloud stack

on:
  workflow_dispatch: # run manually

permissions:
  contents: read

jobs:
  deploy-ansible-playbook:
    runs-on: ubuntu-latest
    concurrency: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Ansible and dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r ansible/requirements.in
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary # will be set by Ansible upon first connection
          name: odt-ansible-key

      - name: Create production .env file
        run: |
          set -euxo pipefail
          touch ansible/files/.env
          echo FLASK_HELMHOLTZ_CLIENT_ID=${{ secrets.FLASK_HELMHOLTZ_CLIENT_ID }} >> ansible/files/.env
          echo FLASK_HELMHOLTZ_CLIENT_SECRET=${{ secrets.FLASK_HELMHOLTZ_CLIENT_SECRET }} >> ansible/files/.env
          echo TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }} >> ansible/files/.env
          echo VITE_TURNSTILE_SITE_KEY=${{ vars.VITE_TURNSTILE_SITE_KEY }} >> ansible/files/.env
          echo FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} >> ansible/files/.env
          echo FRONTEND_URL=${{ vars.FRONTEND_URL }} >> ansible/files/.env
          echo BACKEND_URL=${{ vars.BACKEND_URL }} >> ansible/files/.env
          echo VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }} >> ansible/files/.env
          echo ODT_CLOUD_VERSION=${{ vars.ODT_CLOUD_VERSION }} >> ansible/files/.env
          echo PIPELINE_TIMEOUT_AUTHENTICATED_MULTIPLIER=${{ secrets.PIPELINE_TIMEOUT_AUTHENTICATED_MULTIPLIER }} >> ansible/files/.env

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v9
        with:
          playbook: playbook.yml
          directory: ansible
